### ISSUE TITLE
Code in .h file?

### ISSUE THREAD

**Issue by syntonym** [sjqtentacles/ASCII-Chess-Game#1]
Hey Nixonite! Just saw a link to this repo in an old [reddit thread](http://www.reddit.com/r/gamedevdump/comments/2s52bj/c_ascii_chess_game_wo_ai/). I'm not writing much cpp and wondered why the code for most things is in .h files instead of .cpp files. I thought that (except for well exceptions) declarations should go into .h files and definitions/actual code into .cpp files?

Keep coding
syntonym

**Comment by sjqtentacles** [comment]
Hi I remember that thread.

When I first started learning C++ in high school I used this site http://www.learncpp.com and I recalled that they mentioned header files being useful for storing class declarations 

http://www.learncpp.com/cpp-tutorial/89-class-code-and-header-files/

SO I figured that might be the way to go. I'm also a noob with C++ so don't trust me on this one.
